kind: Deployment
apiVersion: apps/v1
metadata:
  name: httpd-24
  namespace: siva1
  labels:
    app: httpd-24
    app.kubernetes.io/component: httpd-24
    app.kubernetes.io/instance: httpd-24
    app.kubernetes.io/part-of: httpd-24-app
    app.openshift.io/runtime-namespace: siva1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-24
  template:
    metadata:
      labels:
        app: httpd-24
        deploymentconfig: httpd-24
    spec:
      volumes:
        - name: httpd-pvc
          persistentVolumeClaim:
            claimName: httpd-pvc
      containers:
        - name: httpd-24
          image: registry.redhat.io/rhel8/httpd-24
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          volumeMounts:
            - name: httpd-pvc
              mountPath: /httpd-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: httpd-pvc
  namespace: siva1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: openshift-storage.noobaa.io
  volumeMode: Filesystem
